### PR TITLE
Use deepmerge correctly

### PR DESCRIPTION
**Pull request by configurator**
- It only accepts two parameters
- If any of them are null/undefined, it crashes

### CODE REVIEW

**Comment by eXaminator** [comment]
Hey, thanks for the PR.

The order seems wrong. If keys are duplicate when merging, the object on the right will "win". Thus in your current implementation the priority will be: default > options > query

But the priority should be the other way round: query > options > default

Could you verify this and update your PR? After that I will gladly check it out myself and merge it.

**Comment by configurator** [comment]
You're right. I've also run into a few other issues with deepmerge; namely, the script as added to my output failed to run correctly, throwing an error on every __merge call. Unfortunately I couldn't find the cause of these errors.

I've replaced deepmerge with deep-extends instead, which does the same thing, except it supports multiple arguments, and its code is much clearer. Now it seems to work fine, and I've mostly reverted my original commit.

If you look at the combined changelog, https://github.com/eXaminator/closure-loader/pull/21/files, you'll see that the changes, besides replacing the required library, are extremely minimal.

**Comment by eXaminator** [comment]
I'll have a look at it soon. Looks good at first glance, if everything works out I'll take it. :)

**Comment by eXaminator** [comment]
I just released 0.2.0 including your changes

**Pull request merged**
